//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYHIENMAUDANANG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENHVIEN()
        {
            this.KHOAHUYETHOC_TRUYENMAU = new HashSet<KHOAHUYETHOC_TRUYENMAU>();
            this.KHOAXETNGHIEM = new HashSet<KHOAXETNGHIEM>();
        }
    
        public string MaBV { get; set; }
        public string TenBV { get; set; }
        public string NguoiDaiDien { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOAHUYETHOC_TRUYENMAU> KHOAHUYETHOC_TRUYENMAU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOAXETNGHIEM> KHOAXETNGHIEM { get; set; }
    }
}
