//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYHIENMAUDANANG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAP
    {
        public string MaPN { get; set; }
        public string MaNM { get; set; }
        public Nullable<int> TheTichMau { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
    
        public virtual NHOMMAU NHOMMAU { get; set; }
        public virtual PHIEUNHAPMAU PHIEUNHAPMAU { get; set; }
    }
}
