//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYHIENMAUDANANG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHIENMAU
    {
        public string MaCTHM { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public Nullable<int> TheTichMau { get; set; }
        public string TinhTrangSucKhoe { get; set; }
        public string KetQua { get; set; }
        public string ChuThich { get; set; }
        public string MaNV { get; set; }
        public string MaNM { get; set; }
        public string MaDKHM { get; set; }
    
        public virtual PHIEUDANGKYHIENMAU PHIEUDANGKYHIENMAU { get; set; }
        public virtual NHOMMAU NHOMMAU { get; set; }
        public virtual NHANVIENKHOAXETNGHIEM NHANVIENKHOAXETNGHIEM { get; set; }
    }
}
