//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYHIENMAUDANANG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOTHIENMAU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOTHIENMAU()
        {
            this.PHIEUDANGKYHIENMAU = new HashSet<PHIEUDANGKYHIENMAU>();
        }
    
        public string MaDot { get; set; }
        public string TenDot { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> SoLuongDangKyToiDa { get; set; }
        public Nullable<int> SoLuongDangKy { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string MaDVTC { get; set; }
        public string MaKhoa { get; set; }
    
        public virtual DONVITOCHUC DONVITOCHUC { get; set; }
        public virtual KHOAXETNGHIEM KHOAXETNGHIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDANGKYHIENMAU> PHIEUDANGKYHIENMAU { get; set; }
    }
}
