//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYHIENMAUDANANG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDANGKYHIENMAU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDANGKYHIENMAU()
        {
            this.CHITIETHIENMAU = new HashSet<CHITIETHIENMAU>();
        }
    
        public string MaDKHM { get; set; }
        public string TenNguoiHien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string SoCCCD { get; set; }
        public Nullable<System.DateTime> NgayDKHM { get; set; }
        public string MaTV { get; set; }
        public string MaDot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHIENMAU> CHITIETHIENMAU { get; set; }
        public virtual DOTHIENMAU DOTHIENMAU { get; set; }
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
